name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Configuração do Ambiente
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    name: Flake8 + Black
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install flake8 black

      - name: Rodar Flake8
        run: flake8 .

      - name: Rodar Black (checagem)
        run: black . --check

  test:
    name: Testes Unitários
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install pytest pytest-cov httpx

      - name: Rodar testes com cobertura
        run: pytest --cov=app --cov-report=term-missing
